server:
    runMode: debug # debug, release, test
    httpPort: 8080
    shutdownTimeout: 1 # second
    apiVersion: v1

pprof:
    port: 6060

mysql:
    master:
        host: localhost:3306
        username: root
        password: root_password
        dbName: banking
    slave:
        host: localhost:3307
        username: root
        password: root_password
        dbName: banking
    tablePrefix: banking_
    maxIdleConns: 10
    maxOpenConns: 100
    maxLifetime: 2

log:
    maxSize: 10 # megabytes
    maxBackups: 10 # files
    maxAge: 90 # days
    compress: false

apm:
    serviceName: banking
    serverUrl: http://localhost:8200
    # serverUrl: http://apm-server:8200
    secretToken: ''

elasticsearch:
    url: "http://localhost:9200"
    username: ""
    password: ""
    index: "logs-index"

redis:
    cluster:
        addrs:
            - "redis-cluster:7000"
            - "redis-cluster:7001"
            - "redis-cluster:7002"
            - "redis-cluster:7003"
            - "redis-cluster:7004"
            - "redis-cluster:7005"
        password: "redis_password"