server:
    runMode: debug # Set this to "release" for production
    httpPort: 8080
    shutdownTimeout: 1 # second
    apiVersion: v1

pprof:
    port: 6060

mysql:
    master:
        host: mysql-master:3306
        username: root
        password: root_password
        dbName: banking
    slave:
        host: mysql-slave:3306
        username: root
        password: root_password
        dbName: banking
    tablePrefix: banking_
    maxIdleConns: 10
    maxOpenConns: 100
    maxLifetime: 2

log:
    maxSize: 10 # megabytes
    maxBackups: 10 # files
    maxAge: 90 # days
    compress: false

apm:
    serviceName: banking
    serverUrl: http://apm_server:8200
    secretToken: 'apmToken'

elasticsearch:
    url: "http://elasticsearch:9200"
    username: ""
    password: ""
    index: "logs-index"

# redis:
#     cluster:
#         addrs:
#             - "redis-cluster:7000"
#             - "redis-cluster:7001"
#             - "redis-cluster:7002"
#             - "redis-cluster:7003"
#             - "redis-cluster:7004"
#             - "redis-cluster:7005"
#         password: "redis_password"

redis:
    addr: "redis:6379"  # Address for a single Redis instance
    password: "redis_password"

jwt:
    secretKey: "your-secret-key"  # This key is used to sign JWT tokens. Keep it safe and private.
    expirationTime: 24            # Token expiration time in hours
    issuer: "banking-app"         # Token issuer (for validation)
    audience: "banking-users"