// Code generated by MockGen. DO NOT EDIT.
// Source: ./user.go

// Package mock is a generated GoMock package.
package mock

import (
	model "banking/model"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	decimal "github.com/shopspring/decimal"
)

// MockIUserService is a mock of IUserService interface.
type MockIUserService struct {
	ctrl     *gomock.Controller
	recorder *MockIUserServiceMockRecorder
}

// MockIUserServiceMockRecorder is the mock recorder for MockIUserService.
type MockIUserServiceMockRecorder struct {
	mock *MockIUserService
}

// NewMockIUserService creates a new mock instance.
func NewMockIUserService(ctrl *gomock.Controller) *MockIUserService {
	mock := &MockIUserService{ctrl: ctrl}
	mock.recorder = &MockIUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUserService) EXPECT() *MockIUserServiceMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockIUserService) CreateUser(ctx context.Context, user *model.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockIUserServiceMockRecorder) CreateUser(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockIUserService)(nil).CreateUser), ctx, user)
}

// Deposit mocks base method.
func (m *MockIUserService) Deposit(ctx context.Context, userID uint, amount decimal.Decimal) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deposit", ctx, userID, amount)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Deposit indicates an expected call of Deposit.
func (mr *MockIUserServiceMockRecorder) Deposit(ctx, userID, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deposit", reflect.TypeOf((*MockIUserService)(nil).Deposit), ctx, userID, amount)
}

// GetUser mocks base method.
func (m *MockIUserService) GetUser(ctx context.Context, userID uint) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, userID)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockIUserServiceMockRecorder) GetUser(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockIUserService)(nil).GetUser), ctx, userID)
}

// GetUsers mocks base method.
func (m *MockIUserService) GetUsers(ctx context.Context) ([]*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsers", ctx)
	ret0, _ := ret[0].([]*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsers indicates an expected call of GetUsers.
func (mr *MockIUserServiceMockRecorder) GetUsers(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsers", reflect.TypeOf((*MockIUserService)(nil).GetUsers), ctx)
}

// Transfer mocks base method.
func (m *MockIUserService) Transfer(ctx context.Context, fromUserID, toUserID uint, amount decimal.Decimal) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transfer", ctx, fromUserID, toUserID, amount)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Transfer indicates an expected call of Transfer.
func (mr *MockIUserServiceMockRecorder) Transfer(ctx, fromUserID, toUserID, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transfer", reflect.TypeOf((*MockIUserService)(nil).Transfer), ctx, fromUserID, toUserID, amount)
}

// Withdraw mocks base method.
func (m *MockIUserService) Withdraw(ctx context.Context, userID uint, amount decimal.Decimal) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Withdraw", ctx, userID, amount)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Withdraw indicates an expected call of Withdraw.
func (mr *MockIUserServiceMockRecorder) Withdraw(ctx, userID, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Withdraw", reflect.TypeOf((*MockIUserService)(nil).Withdraw), ctx, userID, amount)
}

// MockIUserQueryRepo is a mock of IUserQueryRepo interface.
type MockIUserQueryRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIUserQueryRepoMockRecorder
}

// MockIUserQueryRepoMockRecorder is the mock recorder for MockIUserQueryRepo.
type MockIUserQueryRepoMockRecorder struct {
	mock *MockIUserQueryRepo
}

// NewMockIUserQueryRepo creates a new mock instance.
func NewMockIUserQueryRepo(ctrl *gomock.Controller) *MockIUserQueryRepo {
	mock := &MockIUserQueryRepo{ctrl: ctrl}
	mock.recorder = &MockIUserQueryRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUserQueryRepo) EXPECT() *MockIUserQueryRepoMockRecorder {
	return m.recorder
}

// GetUser mocks base method.
func (m *MockIUserQueryRepo) GetUser(ctx context.Context, userID uint) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, userID)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockIUserQueryRepoMockRecorder) GetUser(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockIUserQueryRepo)(nil).GetUser), ctx, userID)
}

// GetUsers mocks base method.
func (m *MockIUserQueryRepo) GetUsers(ctx context.Context) ([]*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsers", ctx)
	ret0, _ := ret[0].([]*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsers indicates an expected call of GetUsers.
func (mr *MockIUserQueryRepoMockRecorder) GetUsers(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsers", reflect.TypeOf((*MockIUserQueryRepo)(nil).GetUsers), ctx)
}

// MockIUserCommandRepo is a mock of IUserCommandRepo interface.
type MockIUserCommandRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIUserCommandRepoMockRecorder
}

// MockIUserCommandRepoMockRecorder is the mock recorder for MockIUserCommandRepo.
type MockIUserCommandRepoMockRecorder struct {
	mock *MockIUserCommandRepo
}

// NewMockIUserCommandRepo creates a new mock instance.
func NewMockIUserCommandRepo(ctrl *gomock.Controller) *MockIUserCommandRepo {
	mock := &MockIUserCommandRepo{ctrl: ctrl}
	mock.recorder = &MockIUserCommandRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUserCommandRepo) EXPECT() *MockIUserCommandRepoMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockIUserCommandRepo) CreateUser(ctx context.Context, user *model.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockIUserCommandRepoMockRecorder) CreateUser(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockIUserCommandRepo)(nil).CreateUser), ctx, user)
}

// Deposit mocks base method.
func (m *MockIUserCommandRepo) Deposit(ctx context.Context, userID uint, amount decimal.Decimal) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deposit", ctx, userID, amount)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Deposit indicates an expected call of Deposit.
func (mr *MockIUserCommandRepoMockRecorder) Deposit(ctx, userID, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deposit", reflect.TypeOf((*MockIUserCommandRepo)(nil).Deposit), ctx, userID, amount)
}

// Transfer mocks base method.
func (m *MockIUserCommandRepo) Transfer(ctx context.Context, fromUserID, toUserID uint, amount decimal.Decimal) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transfer", ctx, fromUserID, toUserID, amount)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Transfer indicates an expected call of Transfer.
func (mr *MockIUserCommandRepoMockRecorder) Transfer(ctx, fromUserID, toUserID, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transfer", reflect.TypeOf((*MockIUserCommandRepo)(nil).Transfer), ctx, fromUserID, toUserID, amount)
}

// Withdraw mocks base method.
func (m *MockIUserCommandRepo) Withdraw(ctx context.Context, userID uint, amount decimal.Decimal) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Withdraw", ctx, userID, amount)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Withdraw indicates an expected call of Withdraw.
func (mr *MockIUserCommandRepoMockRecorder) Withdraw(ctx, userID, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Withdraw", reflect.TypeOf((*MockIUserCommandRepo)(nil).Withdraw), ctx, userID, amount)
}
