// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package mysql

import (
	"context"
)

// Injectors from wire.go:

func InitMySQL(ctx context.Context) (*MySQL, error) {
	master, err := NewMasterDB(ctx)
	if err != nil {
		return nil, err
	}
	slave, err := NewSlaveDB(ctx)
	if err != nil {
		return nil, err
	}
	mySQL := &MySQL{
		Master: master,
		Slave:  slave,
	}
	return mySQL, nil
}
