definitions:
  user.APIKey:
    properties:
      key:
        type: string
      secret:
        type: string
      userId:
        type: integer
    type: object
  user.CreateAPIKeyResp:
    properties:
      data:
        $ref: '#/definitions/user.APIKey'
    type: object
  user.CreateUserReq:
    properties:
      email:
        type: string
      name:
        maxLength: 20
        minLength: 3
        type: string
      password:
        maxLength: 20
        minLength: 8
        type: string
    required:
    - email
    - name
    - password
    type: object
  user.CreateUserResp:
    properties:
      data:
        $ref: '#/definitions/user.User'
    type: object
  user.GetUsersResp:
    properties:
      data:
        items:
          $ref: '#/definitions/user.User'
        type: array
    type: object
  user.LoginReq:
    properties:
      email:
        type: string
      password:
        maxLength: 20
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  user.LoginResp:
    properties:
      token:
        type: string
    type: object
  user.User:
    properties:
      balance:
        type: number
      email:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  v1.ErrResponse:
    properties:
      msg:
        type: string
    type: object
info:
  contact: {}
  description: This is a sample server celler server.
  title: banking API
  version: 0.0.1
paths:
  /api/v1/user/{userId}:
    get:
      consumes:
      - application/json
      description: Get Users
      parameters:
      - description: user id
        in: path
        name: userId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/user.GetUsersResp'
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/v1.ErrResponse'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/v1.ErrResponse'
      security:
      - BearerAuth: []
      summary: Get Users
      tags:
      - User
  /api/v1/user/apikey:
    post:
      consumes:
      - application/json
      description: Create API Key
      produces:
      - application/json
      responses:
        "201":
          description: success created api key
          schema:
            $ref: '#/definitions/user.CreateAPIKeyResp'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/v1.ErrResponse'
      security:
      - BearerAuth: []
      summary: Create API Key
      tags:
      - User
  /api/v1/user/login:
    post:
      consumes:
      - application/json
      description: Login
      parameters:
      - description: login request
        in: body
        name: LoginReq
        required: true
        schema:
          $ref: '#/definitions/user.LoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/user.LoginResp'
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/v1.ErrResponse'
        "401":
          description: unauthorized
          schema:
            $ref: '#/definitions/v1.ErrResponse'
      summary: Login
      tags:
      - User
  /api/v1/user/register:
    post:
      consumes:
      - application/json
      description: Create User
      parameters:
      - description: create user request
        in: body
        name: CreateUserReq
        schema:
          $ref: '#/definitions/user.CreateUserReq'
      produces:
      - application/json
      responses:
        "201":
          description: success created user
          schema:
            $ref: '#/definitions/user.CreateUserResp'
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/v1.ErrResponse'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/v1.ErrResponse'
      summary: Create User
      tags:
      - User
swagger: "2.0"
