// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package redis

import (
	"context"
)

// Injectors from wire.go:

func InitRedis(ctx context.Context) (*Redis, error) {
	redis, err := NewRedis(ctx)
	if err != nil {
		return nil, err
	}
	return redis, nil
}
