// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package redis

import (
	"context"
)

// Injectors from wire.go:

func InitRedis(ctx context.Context) (*RedisCluster, error) {
	redisCluster, err := NewRedisCluster(ctx)
	if err != nil {
		return nil, err
	}
	return redisCluster, nil
}
